trigger:
  branches:
    include:
    - main
    - uat
    - development
    - feature/deploy

variables:
    dockerRegistryServiceConnection: 'acromnichannel'
    devImageRepository: 'biller/bapbackofficedev'
    uatImageRepository: 'biller/bapbackofficeuat'
    imageRepository: 'biller/bapbackoffice'
    containerRegistry: 'acromnichannel.azurecr.io'
    dockerfilePath: '**/Dockerfile'
    tag: '$(Build.BuildId)'

    vmImageName: 'ubuntu-latest'

stages:
- stage: BuildDEV
  displayName: Build DEV
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/feature/deploy'))
  jobs:
  - job: Build
    displayName: Build DEV
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(devImageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(system.defaultworkingdirectory)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(devImageRepository)
        tags: |
          $(tag)

- stage: BuildUAT
  displayName: Build UAT
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/uat'))
  jobs:
  - job: Build
    displayName: Build UAT
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(uatImageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(system.defaultworkingdirectory)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(uatImageRepository)
        tags: |
          $(tag)

- stage: BuildPROD
  displayName: Build PROD
  condition: and(always(), contains(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Build
    displayName: Build PROD
    pool:
      vmImage: $(vmImageName)
    steps:

    - task: Docker@2
      displayName: Build
      inputs:
        command: build
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        buildContext: $(system.defaultworkingdirectory)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Push
      inputs:
        command: push
        containerRegistry: $(dockerRegistryServiceConnection)
        repository: $(imageRepository)
        tags: |
          $(tag)